language: php

php:
  - 7.3
before_script:
  - travis_retry composer install --prefer-source --no-interaction --dev
script:
  -  XDEBUG_MODE=coverage ./vendor/bin/phpspec run --config=phpspec.yml --no-interaction -v